FROM node:16-alpine
WORKDIR "/app"
COPY ./package.json ./
RUN npm install
COPY ./ ./
RUN mkdir /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache
USER node
CMD [ "npm", "run", "start" ]